ALTER TABLE "Settings" ADD COLUMN "scanIntervalMins" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Settings" ADD COLUMN "azuracastPollIntervalMins" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Settings" ADD COLUMN "recheckIntervalMins" INTEGER NOT NULL DEFAULT 30;
